version: "3.9"

services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app/app
      - ./migration:/app/migration
      - ./alembic.ini:/app/alembic.ini
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      redis:
        condition: service_healthy
    restart: always
# Note: Postgres is now external (Neon). Set DATABASE_URL in .env.docker accordingly.
