"""add towalletid on trasx table

Revision ID: 9000e6290875
Revises: 7c3ae610a684
Create Date: 2025-07-21 18:26:23.273752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9000e6290875'
down_revision: Union[str, None] = '7c3ae610a684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('to_wallet_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'wallets', ['to_wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'to_wallet_id')
    # ### end Alembic commands ###
