"""addd audit model and update trasaction model with to_user and from_user and transaction_direction

Revision ID: c8badcc7363d
Revises: 804d2fd94f14
Create Date: 2025-07-17 05:50:54.395742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8badcc7363d'
down_revision: Union[str, None] = '804d2fd94f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('actor_name', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('resource_summary', sa.String(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('from_user', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('to_user', sa.String(), nullable=True))
    # Create ENUM type before adding the column
    transaction_direction_enum = sa.Enum('CREDIT', 'DEBIT', name='transactiondirection')
    transaction_direction_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('transactions', sa.Column('transaction_direction', transaction_direction_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_direction')
    op.drop_column('transactions', 'to_user')
    op.drop_column('transactions', 'from_user')
    op.drop_table('audit_logs')
    # Drop ENUM type after dropping the column
    transaction_direction_enum = sa.Enum('CREDIT', 'DEBIT', name='transactiondirection')
    transaction_direction_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
