"""update session model

Revision ID: 04211c5e6165
Revises: 83777ec19630
Create Date: 2025-05-05 21:52:04.115753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04211c5e6165'
down_revision: Union[str, None] = '83777ec19630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('terminated_by', sa.Uuid(), nullable=True))
    op.add_column('sessions', sa.Column('termination_reason', sa.String(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'users', ['terminated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'termination_reason')
    op.drop_column('sessions', 'terminated_by')
    # ### end Alembic commands ###
