"""add terms and condition

Revision ID: 04846d7b01b5
Revises: 8026e04a7479
Create Date: 2025-09-19 09:41:00.104062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04846d7b01b5'
down_revision: Union[str, Sequence[str], None] = '8026e04a7479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('orders', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('users', sa.Column('accept_terms_and_conditions', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accept_terms_and_conditions')
    op.alter_column('orders', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('items', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
