"""add acount_holder_name to profile

Revision ID: 05f8737445b2
Revises: f6803bf63dcd
Create Date: 2025-06-05 09:17:43.384456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05f8737445b2"
down_revision: Union[str, None] = "f6803bf63dcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profile", sa.Column("account_holder_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profile", "account_holder_name")
    # ### end Alembic commands ###
