"""change destination and origin from decimal type to str type

Revision ID: 091076f90aad
Revises: 513e0c984067
Create Date: 2025-05-18 00:43:51.197627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091076f90aad'
down_revision: Union[str, None] = '513e0c984067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deliveries', 'origin',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('deliveries', 'destination',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deliveries', 'destination',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.alter_column('deliveries', 'origin',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###
