"""remove order_number from order

Revision ID: 0fd690423ae2
Revises: fc36b7ecadb9
Create Date: 2025-05-05 08:29:39.533319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0fd690423ae2"
down_revision: Union[str, None] = "fc36b7ecadb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("orders_order_number_key", "orders", type_="unique")
    op.drop_column("orders", "order_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "order_number", sa.VARCHAR(length=15), autoincrement=False, nullable=False
        ),
    )
    op.create_unique_constraint("orders_order_number_key", "orders", ["order_number"])
    # ### end Alembic commands ###
