"""add product_url

Revision ID: 10a2e511058b
Revises: 1536298bd375
Create Date: 2025-05-17 07:00:54.632341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a2e511058b'
down_revision: Union[str, None] = '1536298bd375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_images', sa.Column('product_image_urls', sa.String(), nullable=True))
    op.add_column('item_images', sa.Column('package_image_url', sa.String(), nullable=True))
    op.drop_column('item_images', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_images', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('item_images', 'package_image_url')
    op.drop_column('item_images', 'product_image_urls')
    # ### end Alembic commands ###
