"""add origin and destination to Delivey model

Revision ID: 1536298bd375
Revises: 8efffd3b0e18
Create Date: 2025-05-16 20:21:47.886252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1536298bd375'
down_revision: Union[str, None] = '8efffd3b0e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('origin', sa.Numeric(), nullable=True))
    op.add_column('deliveries', sa.Column('destination', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'destination')
    op.drop_column('deliveries', 'origin')
    # ### end Alembic commands ###
