"""add user coordinates

Revision ID: 17223dc7685f
Revises: 3b77473f7cef
Create Date: 2025-09-01 10:03:01.260121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17223dc7685f'
down_revision: Union[str, Sequence[str], None] = '3b77473f7cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_user_loation_coords', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_user_loation_coords')
    # ### end Alembic commands ###
