"""remove delivery_id from review

Revision ID: 1e8fc6491e0f
Revises: 4c69bececf93
Create Date: 2025-06-19 21:33:52.201363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8fc6491e0f'
down_revision: Union[str, None] = '4c69bececf93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_delivery_review', 'reviews', type_='unique')
    op.drop_constraint('reviews_delivery_id_fkey', 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'delivery_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('delivery_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('reviews_delivery_id_fkey', 'reviews', 'deliveries', ['delivery_id'], ['id'])
    op.create_unique_constraint('uq_user_delivery_review', 'reviews', ['reviewer_id', 'delivery_id'])
    # ### end Alembic commands ###
