"""add bike_number to profile

Revision ID: 1f8939dc1bd4
Revises: a0e88e1d2fc4
Create Date: 2025-05-04 10:44:46.384466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f8939dc1bd4"
down_revision: Union[str, None] = "a0e88e1d2fc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profile", sa.Column("bike_number", sa.String(), nullable=True))
    op.create_unique_constraint(None, "profile", ["bike_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profile", type_="unique")
    op.drop_column("profile", "bike_number")
    # ### end Alembic commands ###
