"""add side to item

Revision ID: 28bbc40978e4
Revises: 92bed70cf501
Create Date: 2025-06-23 16:56:38.611819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28bbc40978e4"
down_revision: Union[str, None] = "92bed70cf501"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("side", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "side")
    # ### end Alembic commands ###
