"""add PRODUCT to item enum

Revision ID: 33123eb63224
Revises: 0eae04defd9e
Create Date: 2025-05-11 08:35:10.949477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33123eb63224"
down_revision: Union[str, None] = "0eae04defd9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_name_item", "items", ["name", "user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_name_item", "items", type_="unique")
    # ### end Alembic commands ###
