"""add deleted flag

Revision ID: 35a92336f7de
Revises: af25e0e9e263
Create Date: 2025-09-17 16:18:26.657035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a92336f7de'
down_revision: Union[str, Sequence[str], None] = 'af25e0e9e263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('orders', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_deleted')
    op.drop_column('items', 'is_deleted')
    # ### end Alembic commands ###
