"""add state to profile model

Revision ID: 3b77473f7cef
Revises: eebd229d9ae4
Create Date: 2025-08-29 18:01:37.377511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b77473f7cef'
down_revision: Union[str, Sequence[str], None] = 'eebd229d9ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'tx_ref',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('profile', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'state')
    op.alter_column('orders', 'tx_ref',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
