"""remove size and color models

Revision ID: 413e4f210520
Revises: fdf1ae3706b4
Create Date: 2025-05-11 14:20:51.506700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "413e4f210520"
down_revision: Union[str, None] = "fdf1ae3706b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sizes")
    op.drop_table("colors")
    op.add_column("items", sa.Column("sizes", sa.String(), nullable=True))
    op.add_column("items", sa.Column("colors", sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "colors")
    op.drop_column("items", "sizes")
    op.create_table(
        "colors",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("color", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("item_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name="colors_item_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="colors_pkey"),
        sa.UniqueConstraint("color", name="colors_color_key"),
    )
    op.create_table(
        "sizes",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("size", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("item_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name="sizes_item_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="sizes_pkey"),
        sa.UniqueConstraint("size", name="sizes_size_key"),
    )
    # ### end Alembic commands ###
