"""add customer to review

Revision ID: 4c69bececf93
Revises: b55cdae78355
Create Date: 2025-06-18 10:53:17.930063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c69bececf93'
down_revision: Union[str, None] = 'b55cdae78355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('customer_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'issues', 'users', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'customer_id')
    # ### end Alembic commands ###
