"""change duration from decimal type to str type

Revision ID: 513e0c984067
Revises: bd875fb93fce
Create Date: 2025-05-17 21:08:57.733432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513e0c984067'
down_revision: Union[str, None] = 'bd875fb93fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deliveries', 'duration',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deliveries', 'duration',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    # ### end Alembic commands ###
