"""add distance and duration to deliver model

Revision ID: 55357218f785
Revises: 04211c5e6165
Create Date: 2025-05-06 07:52:17.450234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55357218f785"
down_revision: Union[str, None] = "04211c5e6165"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deliveries", sa.Column("distance", sa.Numeric(), nullable=True))
    op.add_column("deliveries", sa.Column("duration", sa.Numeric(), nullable=True))
    op.add_column("orders", sa.Column("order_number", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "orders", ["order_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="unique")
    op.drop_column("orders", "order_number")
    op.drop_column("deliveries", "duration")
    op.drop_column("deliveries", "distance")
    # ### end Alembic commands ###
