"""add store_name to profile

Revision ID: 5ba662f6e5b7
Revises: 53cfd6503d44
Create Date: 2025-06-17 08:41:09.849499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba662f6e5b7'
down_revision: Union[str, None] = '53cfd6503d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('store_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'profile', ['store_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='unique')
    op.drop_column('profile', 'store_name')
    # ### end Alembic commands ###
