"""make profile_image nullable

Revision ID: 61fc5c289841
Revises: f8018d158d20
Create Date: 2025-05-24 20:20:26.544478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61fc5c289841"
down_revision: Union[str, None] = "f8018d158d20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profile_images", "profile_image_url", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profile_images",
        "profile_image_url",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
