"""update coordinates

Revision ID: 679a02e37b3b
Revises: 17223dc7685f
Create Date: 2025-09-01 10:24:50.802643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '679a02e37b3b'
down_revision: Union[str, Sequence[str], None] = '17223dc7685f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_user_location_coords', sa.JSON(), nullable=True))
    op.drop_column('users', 'current_user_loation_coords')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_user_loation_coords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('users', 'current_user_location_coords')
    # ### end Alembic commands ###
