"""add payment_status to order

Revision ID: 6f1a5bbaba17
Revises: 091076f90aad
Create Date: 2025-05-19 21:50:27.493781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1a5bbaba17'
down_revision: Union[str, None] = '091076f90aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_status', sa.Enum('FAILED', 'PAID', 'CANCELLED', 'PENDING', 'COMPLETED', 'SUCCESSFUL', name='paymentstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###
