"""add sender phone and rider phone to delivery

Revision ID: 75d571bbf3c4
Revises: c311e853753b
Create Date: 2025-06-09 03:25:09.757522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d571bbf3c4'
down_revision: Union[str, None] = 'c311e853753b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('sender_phone_number', sa.String(), nullable=True))
    op.add_column('deliveries', sa.Column('rider_phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'rider_phone_number')
    op.drop_column('deliveries', 'sender_phone_number')
    # ### end Alembic commands ###
