"""add deleted flag

Revision ID: 8026e04a7479
Revises: 35a92336f7de
Create Date: 2025-09-17 16:25:38.596577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8026e04a7479'
down_revision: Union[str, Sequence[str], None] = '35a92336f7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_deleted')
    op.drop_column('items', 'is_deleted')
    # ### end Alembic commands ###
