"""add terms and condition

Revision ID: 80c50e4e94f4
Revises: 04846d7b01b5
Create Date: 2025-09-19 09:57:48.103465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c50e4e94f4'
down_revision: Union[str, Sequence[str], None] = '04846d7b01b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accept_terms_and_conditions', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accept_terms_and_conditions')
    # ### end Alembic commands ###
