"""update models

Revision ID: 8efffd3b0e18
Revises: 2fb67cf2978c
Create Date: 2025-05-16 05:39:45.273184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8efffd3b0e18"
down_revision: Union[str, None] = "2fb67cf2978c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_items", "additional_info")
    op.add_column("orders", sa.Column("additional_info", sa.String(), nullable=True))
    op.create_unique_constraint(None, "profile", ["user_id"])
    op.create_unique_constraint(None, "profile_images", ["profile_id"])
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "account_status",
            sa.Enum("PENDING", "CONFIRMED", name="accountstatus"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_tokens", "account_status")
    op.drop_constraint(None, "profile_images", type_="unique")
    op.drop_constraint(None, "profile", type_="unique")
    op.drop_column("orders", "additional_info")
    op.add_column(
        "order_items",
        sa.Column("additional_info", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
