"""add rider_is_suspended_for_order_cancel, order_cancel_count to User model

Revision ID: 94c88d8e6d34
Revises: a297396ae225
Create Date: 2025-05-12 16:35:42.407565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94c88d8e6d34'
down_revision: Union[str, None] = 'a297396ae225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failed_payments')
    op.add_column('users', sa.Column('rider_is_suspended_for_order_cancel', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('rider_is_suspension_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('order_cancel_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'order_cancel_count')
    op.drop_column('users', 'rider_is_suspension_until')
    op.drop_column('users', 'rider_is_suspended_for_order_cancel')
    op.create_table('failed_payments',
    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('transaction_id', name='failed_payments_pkey')
    )
    # ### end Alembic commands ###
