"""add rand_total attr to order model

Revision ID: 9527882ac150
Revises: 9b0849743f1d
Create Date: 2025-08-14 05:01:23.547798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9527882ac150'
down_revision: Union[str, Sequence[str], None] = '9b0849743f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('grand_total', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'grand_total')
    # ### end Alembic commands ###
