"""update models

Revision ID: 99ae0b8f61a0
Revises: 05f8737445b2
Create Date: 2025-06-06 08:18:46.507096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99ae0b8f61a0"
down_revision: Union[str, None] = "05f8737445b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("deliveries_dispatch_id_fkey", "deliveries", type_="foreignkey")
    op.drop_constraint("deliveries_sender_id_fkey", "deliveries", type_="foreignkey")
    op.drop_constraint("deliveries_vendor_id_fkey", "deliveries", type_="foreignkey")
    op.drop_constraint("deliveries_rider_id_fkey", "deliveries", type_="foreignkey")
    op.create_foreign_key(
        None, "deliveries", "users", ["rider_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "deliveries", "users", ["vendor_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "deliveries", "users", ["sender_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "deliveries", "users", ["dispatch_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint("profile_user_id_fkey", "profile", type_="foreignkey")
    op.create_foreign_key(
        None, "profile", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("users_dispatcher_id_fkey", "users", type_="foreignkey")
    op.create_foreign_key(
        None, "users", "users", ["dispatcher_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        "users_dispatcher_id_fkey", "users", "users", ["dispatcher_id"], ["id"]
    )
    op.drop_constraint(None, "profile", type_="foreignkey")
    op.create_foreign_key(
        "profile_user_id_fkey", "profile", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "deliveries", type_="foreignkey")
    op.drop_constraint(None, "deliveries", type_="foreignkey")
    op.drop_constraint(None, "deliveries", type_="foreignkey")
    op.drop_constraint(None, "deliveries", type_="foreignkey")
    op.create_foreign_key(
        "deliveries_rider_id_fkey", "deliveries", "users", ["rider_id"], ["id"]
    )
    op.create_foreign_key(
        "deliveries_vendor_id_fkey", "deliveries", "users", ["vendor_id"], ["id"]
    )
    op.create_foreign_key(
        "deliveries_sender_id_fkey", "deliveries", "users", ["sender_id"], ["id"]
    )
    op.create_foreign_key(
        "deliveries_dispatch_id_fkey", "deliveries", "users", ["dispatch_id"], ["id"]
    )
    # ### end Alembic commands ###
