"""add idempotent_id to wallet and transaction model

Revision ID: 9ec15b630605
Revises: 679a02e37b3b
Create Date: 2025-09-01 14:21:41.073325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec15b630605'
down_revision: Union[str, Sequence[str], None] = '679a02e37b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_unique_constraint('unique_tx_per_wallet_direction', 'transactions', ['tx_ref', 'wallet_id', 'transaction_direction'])
    op.add_column('wallets', sa.Column('idempotency_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'idempotency_key')
    op.drop_constraint('unique_tx_per_wallet_direction', 'transactions', type_='unique')
    op.drop_column('transactions', 'idempotency_key')
    # ### end Alembic commands ###
