"""add size and color to OrderItem model

Revision ID: a297396ae225
Revises: 413e4f210520
Create Date: 2025-05-12 07:54:46.090828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a297396ae225'
down_revision: Union[str, None] = '413e4f210520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_payments',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('total_cost', sa.Numeric(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.add_column('order_items', sa.Column('additional_info', sa.String(), nullable=True))
    op.add_column('order_items', sa.Column('sizes', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('order_items', sa.Column('colors', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'colors')
    op.drop_column('order_items', 'sizes')
    op.drop_column('order_items', 'additional_info')
    op.drop_table('failed_payments')
    # ### end Alembic commands ###
