"""remove product_url

Revision ID: b539d3b1eb31
Revises: 10a2e511058b
Create Date: 2025-05-17 07:20:03.425813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b539d3b1eb31"
down_revision: Union[str, None] = "10a2e511058b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item_images", sa.Column("url", sa.String(), nullable=False))
    op.drop_column("item_images", "package_image_url")
    op.drop_column("item_images", "product_image_urls")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item_images",
        sa.Column(
            "product_image_urls", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "item_images",
        sa.Column(
            "package_image_url", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("item_images", "url")
    # ### end Alembic commands ###
