"""remove unique constraint from item

Revision ID: bd875fb93fce
Revises: 34a9e81debd0
Create Date: 2025-05-17 14:18:20.048472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd875fb93fce'
down_revision: Union[str, None] = '34a9e81debd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_name_item', 'items', type_='unique')
    op.create_index('uq_name_user_non_package', 'items', ['name', 'user_id'], unique=True, postgresql_where=sa.text("item_type != 'PACKAGE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_name_user_non_package', table_name='items', postgresql_where=sa.text("item_type != 'PACKAGE'"))
    op.create_unique_constraint('uq_name_item', 'items', ['name', 'user_id'])
    # ### end Alembic commands ###
