"""add sequence to order

Revision ID: c2030206d3e1
Revises: 704e8ab5a0b4
Create Date: 2025-05-05 08:01:59.067781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c2030206d3e1"
down_revision: Union[str, None] = "704e8ab5a0b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders", "amount_due_vendor", existing_type=sa.NUMERIC(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders", "amount_due_vendor", existing_type=sa.NUMERIC(), nullable=True
    )
    # ### end Alembic commands ###
