"""remove delivery_id from report

Revision ID: d5c94ec5b1d0
Revises: d387a965bd11
Create Date: 2025-07-31 22:28:12.839382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5c94ec5b1d0"
down_revision: Union[str, Sequence[str], None] = "d387a965bd11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "profile", ["user_id"])
    op.create_unique_constraint(None, "profile_images", ["profile_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profile_images", type_="unique")
    op.drop_constraint(None, "profile", type_="unique")
    # ### end Alembic commands ###
