"""add email and phone verification

Revision ID: deb0b01524c2
Revises: 55357218f785
Create Date: 2025-05-07 22:55:14.006637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb0b01524c2'
down_revision: Union[str, None] = '55357218f785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_number',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1000, increment=1),
               existing_nullable=True)
    op.add_column('profile', sa.Column('is_phone_verified', sa.Boolean(), nullable=False))
    op.add_column('profile', sa.Column('phone_verification_code', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('phone_verification_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verification_expires', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['reset_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email_verification_expires')
    op.drop_column('users', 'email_verification_code')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    op.drop_column('profile', 'phone_verification_expires')
    op.drop_column('profile', 'phone_verification_code')
    op.drop_column('profile', 'is_phone_verified')
    op.alter_column('orders', 'order_number',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###
