"""add tx_ref attr to order and transaction model

Revision ID: eebd229d9ae4
Revises: 9527882ac150
Create Date: 2025-08-14 11:39:02.506027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eebd229d9ae4"
down_revision: Union[str, Sequence[str], None] = "9527882ac150"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("tx_ref", sa.Uuid(), nullable=True))
    op.add_column("transactions", sa.Column("tx_ref", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "tx_ref")
    op.drop_column("orders", "tx_ref")
    # ### end Alembic commands ###
