"""change datetime to time in opening and closing hour of Profile model

Revision ID: f8018d158d20
Revises: 6f1a5bbaba17
Create Date: 2025-05-24 10:24:54.436402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8018d158d20'
down_revision: Union[str, None] = '6f1a5bbaba17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    op.alter_column('profile', 'opening_hours',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=True)
    op.alter_column('profile', 'closing_hours',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'closing_hours',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('profile', 'opening_hours',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('orders', sa.Column('payment_status', postgresql.ENUM('FAILED', 'PAID', 'CANCELLED', 'PENDING', 'COMPLETED', 'SUCCESSFUL', name='paymentstatus'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
