"""add sequence to order

Revision ID: fc36b7ecadb9
Revises: 60bf1e117947
Create Date: 2025-05-05 08:26:27.428221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc36b7ecadb9"
down_revision: Union[str, None] = "60bf1e117947"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "order_number",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=15),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "order_number",
        existing_type=sa.String(length=15),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
