"""add fk to size and color models

Revision ID: fdf1ae3706b4
Revises: 0dd42e0c5261
Create Date: 2025-05-11 09:37:15.632605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf1ae3706b4'
down_revision: Union[str, None] = '0dd42e0c5261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colors', sa.Column('item_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'colors', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.add_column('sizes', sa.Column('item_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'sizes', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sizes', type_='foreignkey')
    op.drop_column('sizes', 'item_id')
    op.drop_constraint(None, 'colors', type_='foreignkey')
    op.drop_column('colors', 'item_id')
    # ### end Alembic commands ###
